background_opacity 0.8
dynamic_background_opacity yes
font_size 9.5
# +- 1.5 per change  

cursor_shape block    
# set default kitty cursor to block
shell_integration no-cursor
# prevent CLI and TUI from overriding the cursor
